### ISSUE TITLE
New virtual machine type for x86

### ISSUE THREAD

**Issue by sameo** [intel/nemu#11]
## Rationale
We want to define a minimal, legacy and emulation free, based on virtual hardware, x86_64 machine type for QEMU. Existing machine types (pc and q35) try to emulate an actual chipsets (piix and q35 respectively), pulling requirements for emulating various pieces of hardware and buses (PCI, ISA, MCH, LPC, etc). 
This increases the hypervisor's attack surface together with its implementation complexity for no technical reasons, as typical workloads do not have direct dependencies on such hardware definitions or even availability.

Instead, defining a new machine type based on top-down requirements could simplify the overall hypervisor implementation by only providing strictly virtualized and non emulated resources (CPU, memory, interrupts, timers and generic I/O devices) to cloud bound workloads. The overall hardware platform this machine type exposes is virtual and only provides the minimal set of features and devices modern cloud workloads would need.

There already are a few existing implementations for a virtual hardware platform approach: QEMU's [ARM virt machine type](https://github.com/qemu/qemu/blob/master/hw/arm/virt.c), [kvmtool](https://git.kernel.org/pub/scm/linux/kernel/git/will/kvmtool.git/) and [Hyper-v generation 2 VMs](https://blogs.technet.microsoft.com/jhoward/2013/10/24/hyper-v-generation-2-virtual-machines-part-1/).

## Description

This virtual hardware machine type has the following characteristics:

* **ACPI**
  * Single hardware enumeration method. 
  * ACPI Hardware reduced mode only.
  * Reset method, no i8042 emulation
* **Guest firmware**
  * No legacy BIOS
  * UEFI (OVMF) and qboot
* **Virtio based**
  * virtio-pci by default
  * virtio-scsi
  * virtio-nvme
* **Direct device assignment**
  * vfio-pci
* **Interrupt controller**
  * In-kernel and split implementations supported
* **Reduced PIC support**
  * For early boot, real mode support, timer only
* **Clock source**
  * `kvm-clock`
* **No RTC**
  * Either emulate the couple of RTC CMOS IO ports, or fix OVMF.
* **No PCI bus**
  * PCI segments only, no PCI bridges
* **No north or south bridge emulation (MCH, LPC, PCH)**
* **No ISA**
  * PIO basic serial port support on UART ports, for early debugging purposes. Output only. 
* **Reduced CPU models support**
  * Anything that supports x2APIC and flexpriority

## TODO
- [ ] Implement a `virt` machine type under hw/i386 for upstream QEMU
  - [ ] Simplify OVMF to support the new machine type
- [ ] Upstream `i386/virt`
- [ ] Apply code reduction scripts to QEMU 2.12 with only `i386/virt` and `arm/virt` as the supported machine types
  - [ ] Build a new NEMU branch based on the above code reduced QEMU

**Comment by bonzini** [comment]
Some notes:

- the ARM virt machine type is not a "virtual hardware platform".  It has PL011 serial, PL031 RTC, PL061 GPIO controller, a generic PCIe bridge, fw_cfg for the firmware to get data from QEMU, and emulated
flash.  The idea behind the ARM virt machine type is simply to make everything discoverable via device tree; the "virtualness" of it is simply that the device tree is provided by QEMU and not embedded into something like U-Boot or Linux.

- UEFI runtime services need to provide an RTC, so you need to emulate one.

- without MCH, you'll have to find a different way to handle SMRAM.

- no ISA means no serial port for early boot messages, no debug port for firmware logs, and more painful debugging in general.  I'm not sure that's a good idea.  Of course you don't want stuff like IDE or floppy, but that's orthogonal to having ISA.

- no LPC also means no hotplug (on q35; on PIIX hotplug was part of the SMBus controller, which you probably don't want anyway).  So you'd have to reinvent something very similar to a PCH anyway in order to provide hotplug.

**Comment by rbradford** [comment]
This project is no longer active and being archived. Cloud Hypervisor is the successor: https://github.com/cloud-hypervisor/cloud-hypervisor
